apiVersion: v1
kind: Service
metadata:
  name: conversor-bitcoin-service
  namespace: applications
spec:
  type: NodePort
  selector:
    app: conversor-bitcoin
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
